name: 'Setup asset of Github Releases'
description: 'GitHub Action for gh-setup'
branding:
  icon: 'zap'
  color: 'gray-dark'
inputs:
  github-token:
    description: The GitHub token
    default: ${{ github.token }}
    required: false
  repo:
    description: "Target repository ([HOST/]OWNER/REPO)"
    required: true
  version:
    description: "Release version"
    default: ""
    required: false
  os:
    description: "Specify OS of asset"
    default: ""
    required: false
  arch:
    description: "Specify arch of asset"
    default: ""
    required: false
  match:
    description: "Regexp to match asset name"
    default: ""
    required: false
  bin-dir:
    description: "Executable path"
    default: ""
    required: false
  bin-match:
    description: "Regexp to match bin path in asset"
    default: ""
    required: false
  checksum:
    description: "Checksum of asset"
    default: ""
    required: false
  force:
    description: "Enable force setup"
    default: ""
    required: false
  strict:
    description: "Require strict match"
    default: ""
    required: false
  skip-content-type-check:
    description: "Skip check content-type of assets"
    default: ""
    required: false
  verify-attestation:
    description: "Enable attestation verification using 'gh attestation verify'"
    default: ""
    required: false
  attestation-flags:
    description: "Additional flags to pass to 'gh attestation verify'"
    default: ""
    required: false
  gh-setup-version:
    description: "Version of gh-setup"
    default: "v1.11.6"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
